-- Create schema for Guardiao da Cyca App

-- 1. Profiles Table
-- Stores user profile information, linked to the auth.users table.
create table public.profiles (
  id uuid not null primary key references auth.users (id) on delete cascade,
  name text not null,
  nickname text,
  age int,
  conditions text[],
  potassium_level float8
);

-- Enable RLS and set policies for profiles
alter table public.profiles enable row level security;

create policy "Users can view their own profile." on public.profiles
  for select using (auth.uid() = id);

create policy "Users can update their own profile." on public.profiles
  for update using (auth.uid() = id);

-- 2. Medications Table
-- Stores the list of medications for a user.
create table public.medications (
  id uuid not null default gen_random_uuid() primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null,
  dosage text,
  "time" text,
  created_at timestamptz not null default now()
);

-- Enable RLS and set policies for medications
alter table public.medications enable row level security;

create policy "Users can manage their own medications." on public.medications
  for all using (auth.uid() = user_id);

-- 3. Medication Log Table
-- Tracks which medications were taken on which day.
create table public.medication_log (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    medication_id uuid not null references public.medications(id) on delete cascade,
    taken_at date not null default now(),
    unique(user_id, medication_id, taken_at)
);

-- Enable RLS and set policies for medication_log
alter table public.medication_log enable row level security;

create policy "Users can manage their own medication logs." on public.medication_log
  for all using (auth.uid() = user_id);

-- 4. Exam Records Table
-- Stores medical exam results.
create table public.exam_records (
  id uuid not null default gen_random_uuid() primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  date date not null,
  image_url text not null, -- URL to the image in Supabase Storage
  potassium float8,
  glucose float8,
  creatinine float8,
  created_at timestamptz not null default now()
);

-- Enable RLS and set policies for exam_records
alter table public.exam_records enable row level security;

create policy "Users can manage their own exam records." on public.exam_records
  for all using (auth.uid() = user_id);

-- 5. Purchase Records Table
-- Stores grocery purchase history and AI feedback.
create table public.purchase_records (
  id uuid not null default gen_random_uuid() primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  date date not null,
  items text[],
  feedback text,
  created_at timestamptz not null default now()
);

-- Enable RLS and set policies for purchase_records
alter table public.purchase_records enable row level security;

create policy "Users can manage their own purchase records." on public.purchase_records
  for all using (auth.uid() = user_id);

-- 6. Food Preferences Table
-- Stores user's food likes and dislikes.
create table public.food_preferences (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  food text not null,
  preference text not null, -- 'like' or 'dislike'
  created_at timestamptz not null default now(),
  unique(user_id, food)
);

-- Enable RLS and set policies for food_preferences
alter table public.food_preferences enable row level security;

create policy "Users can manage their own food preferences." on public.food_preferences
  for all using (auth.uid() = user_id);

-- 7. Document Records Table
-- Stores important user documents.
create table public.document_records (
  id uuid not null default gen_random_uuid() primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  title text not null,
  image_url text not null, -- URL to the image in Supabase Storage
  created_at timestamptz not null default now()
);

-- Enable RLS and set policies for document_records
alter table public.document_records enable row level security;

create policy "Users can manage their own documents." on public.document_records
  for all using (auth.uid() = user_id);

-- 8. Supabase Storage Buckets
-- Create buckets for exams and documents.
insert into storage.buckets (id, name, public) values ('exams', 'exams', true) on conflict (id) do nothing;
insert into storage.buckets (id, name, public) values ('documents', 'documents', true) on conflict (id) do nothing;

-- Storage RLS Policies
create policy "Users can upload to their own folder in exams bucket" on storage.objects
  for insert with check (bucket_id = 'exams' and auth.uid()::text = (storage.foldername(name))[1]);

create policy "Users can view their own exams" on storage.objects
  for select using (bucket_id = 'exams' and auth.uid()::text = (storage.foldername(name))[1]);

create policy "Users can delete their own exams" on storage.objects
  for delete using (bucket_id = 'exams' and auth.uid()::text = (storage.foldername(name))[1]);

create policy "Users can upload to their own folder in documents bucket" on storage.objects
  for insert with check (bucket_id = 'documents' and auth.uid()::text = (storage.foldername(name))[1] and (storage.foldername(name))[2] = 'docs');

create policy "Users can view their own documents" on storage.objects
  for select using (bucket_id = 'documents' and auth.uid()::text = (storage.foldername(name))[1]);

create policy "Users can delete their own documents" on storage.objects
  for delete using (bucket_id = 'documents' and auth.uid()::text = (storage.foldername(name))[1]);
